spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: springboot2
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/springboot2?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=UTC
  mvc:
    dispatch-options-request: true
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true
    hostname: localhost
